Parameters:
  App:
    Type: String
    Description: diet
  Env:
    Type: String
    Description: test
  Name:
    Type: String
    Description: diet-helper-service-test-diet
Resources:
  TextTractAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                  "s3:*",
                  "s3-object-lambda:*"
              ],
              "Resource": "*"
            },
            {
              "Effect": "Allow",
              "Action": [
                  "textract:*"
              ],
              "Resource": "*"
            }
          ]
        }
Outputs:
  # 1. You need to output the IAM ManagedPolicy so that Copilot can add it as a managed policy to your ECS task role.
  TextTractAccessPolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref TextTractAccessPolicy